FROM golang:1.24-alpine AS builder

WORKDIR /build

COPY go.mod go.sum ./
COPY vendor/ vendor/
COPY . .

RUN CGO_ENABLED=0 go build -o addr .

FROM alpine:3.21

COPY --from=builder /build/addr /usr/local/bin/addr

CMD ["addr", "-listenPort", ":1333"]

EXPOSE 1333
